THISDIR2 := "${@os.path.dirname(bb.data.getVar('FILE', d, True))}"

# Patch manually applied because it patches source code generated by configure
#do_configure_append() {
#	cd ${S}
#    patch -p1 < ${THISDIR2}/${PN}/0001-seco-qtbase.patch
#}

